export const environment = {
  production: false,
  apiBaseUrl: 'http://localhost:8080',
  appStoreUrl: 'https://apps.apple.com/app/nutriplus',
  playStoreUrl: 'https://play.google.com/store/apps/details?id=br.com.nutriplus',
  androidApkDownloadUrl: '/downloads/nutriplus.apk',
  androidApkVersionLabel: 'v1.1.2',
  iosTestFlightUrl: '',
  iosAdHocManifestPath: '',
  iosVersionLabel: 'v1.1.2',
  gaId: 'G-L11DG3Z3ZC',
  siteUrl: 'http://localhost:4200',
  mercadoPagoPublicKey: '',
  termsVersion: '1.0',
  privacyVersion: '1.0',
};
